### ISSUE TITLE
"Could not find" for installed package with null author

### ISSUE THREAD

**Issue by abc-mikey** [tadzik/rakudobrew#102]
I installed rakudobrew and panda with it, then used panda to install the `Task::Star` packages.  

```
panda install Task::Star
```

However when I tried to test one of the packages that it installed `Term::ANSIColor` it couldn't find it.

```
perl6 -e 'use v6; use Term::ANSIColor;'
===SORRY!===
Could not find Term::ANSIColor at line 1 in:
    /home/michael/.perl6
    /home/michael/.rakudobrew/moar-nom/install/share/perl6/site
    /home/michael/.rakudobrew/moar-nom/install/share/perl6/vendor
    /home/michael/.rakudobrew/moar-nom/install/share/perl6
    CompUnit::Repository::AbsolutePath<190578264>
    CompUnit::Repository::NQP<191340712>
    CompUnit::Repository::Perl5<191340736>
```

I found the file that appeared to define where it was installed and noticed that the author was `null`.

```
{
  "files" : { },
  "name" : "Terminal::ANSIColor",
  "provides" : {
    "Terminal::ANSIColor" : {
      "lib/Terminal/ANSIColor.pm" : {
        "cver" : "2016.08.1-46-g6a8278c",
        "file" : "37E2E5D01D62E5D0E4F3CBBCE0D817264CD0C9E3",
        "time" : 1472301598.87669
      }
    }
  },
  "auth" : null,
  "ver" : "*"
}
```

I tried changing this to `"test"` and it will now find the package as expected.

**Comment by tadzik** [comment]
Huh, very odd! It's not really a rakudobrew bug (seems to be rooted in the precompilation system itself), so I forwarded it to appropriate people to see if it's still a thing and if it can be fixed. Thanks for the report!
