### ISSUE TITLE
Failed to build panda

### ISSUE THREAD

**Issue by yogin25** [tadzik/rakudobrew#111]
i installed rakudo with rakudobrew and it worked
now building panda fails with this aoutput:

Already on 'master'
Your branch is up-to-date with 'origin/master'.
error: pathspec 'nom' did not match any file(s) known to git.
panda for nom not found
Installing latest panda instead.
==> Bootstrapping Panda
==> Installing panda from a local directory '/home/my_home/.rakudobrew/moar-nom/panda'
==> panda depends on File::Find, Shell::Command, JSON::Fast, File::Which
==> Shell::Command depends on File::Find
==> Fetching File::Find
==> Building File::Find
==> Testing File::Find
Unhandled exception: Failed to write to filehandle: NULL string given
   at gen/moar/stage2/NQPHLL.nqp:1707  (/home/my_home/.rakudobrew/moar-nom/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from src/Perl6/Compiler.nqp:27  (/home/my_home/.rakudobrew/moar-nom/install/share/nqp/lib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:1653  (/home/my_home/.rakudobrew/moar-nom/install/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/main.nqp:47  (/home/my_home/.rakudobrew/moar-nom/install/share/perl6/runtime/perl6.moarvm:MAIN)
 from gen/moar/main.nqp:38  (/home/my_home/.rakudobrew/moar-nom/install/share/perl6/runtime/perl6.moarvm:<mainline>)
 from <unknown>:1  (/home/my_home/.rakudobrew/moar-nom/install/share/perl6/runtime/perl6.moarvm:<main>)
 from <unknown>:1  (/home/my_home/.rakudobrew/moar-nom/install/share/perl6/runtime/perl6.moarvm:<entry>)
The spawned command '/home/my_home/.rakudobrew/bin/../moar-nom/install/bin/perl6' exited unsuccessfully (exit code: 1)
  in sub MAIN at bootstrap.pl line 68
  in block <unit> at bootstrap.pl line 9

Failed running /home/my_home/.rakudobrew/bin/../moar-nom/install/bin/perl6 bootstrap.pl at /home/my_home/.rakudobrew/bin/rakudobrew line 58.
	main::run("/home/my_home/.rakudobrew/bin/../moar-nom/install/bin/perl6 b"...) called at /home/my_home/.rakudobrew/bin/rakudobrew line 528
	main::build_panda(undef, undef) called at /home/my_home/.rakudobrew/bin/rakudobrew line 352
	main::build_impl("panda", undef, "") called at /home/my_home/.rakudobrew/bin/rakudobrew line 116

i am using archlinux on a pc

**Comment by tadzik** [comment]
Hi,
panda's not mainained and supported in rakudobrew anymore. Please use [zef](github.com/ugexe/zef) instead.
