### ISSUE TITLE
module executable scripts are not on PATH

### ISSUE THREAD

**Issue by hkdtam** [tadzik/rakudobrew#132]
I found that, after zef install cro and p6doc, the resulting executable scripts were placed under

`/home/username/.rakudobrew/moar-master/install/share/perl6/site/bin/`

instead of a more anticipated location, like

`/home/username/.rakudobrew/bin/`

should I just hardcode the former into PATH or is there any recommended practice to deal with the situation?

Thanks in advance.

**Comment by skaji** [comment]
https://github.com/tadzik/rakudobrew#making-new-scripts-available
```
After you have installed new modules and scripts with zef or panda, you can run

  $ rakudobrew rehash

to make the scripts available in ~/.rakudobrew/bin and thus your PATH.
```

**Comment by hkdtam** [comment]
Oh thanks, that is the right practice, my bad, should have RTFM.
