### ISSUE TITLE
Travis broken

### ISSUE THREAD

**Issue by masak** [tadzik/rakudobrew#134]
I think #133 broke perl6 Travis.

I'm not at a computer right now, so I can't debug it all that deeply. But see https://travis-ci.org/masak/007/builds/522665566 for a failing build that works locally.

**Comment by masak** [comment]
Ping @patzim and @niner who might have some insight into why the breakage.

**Comment by masak** [comment]
At a computer now. The error message is this:

```
$ rakudobrew build moar
The shell hook required to use rakudobrew in 'env' mode and use the 'shell' command seems not to be installed.
Run 'rakudobrew init' for installation instructions.
```

The `if` statement that triggers was added in #133: [this one](https://github.com/tadzik/rakudobrew/pull/133/files#diff-eacca5be9253a97fbfa511b258281c7bR75). I'm guessing it's `get_brew_mode() eq 'env'` that triggers true in this case.

Not sure it this point whether this is a bug in `rakudobrew`, or whether the Perl 6 support for Travis-CI just needs to be reconfigured. (In which case I should probably report it at [the Travis discussion forum](https://travis-ci.community/c/languages/perl6).)

**Comment by masak** [comment]
Scanning the IRC logs. rindolf just got informed this was due to [network related problems](https://colabti.org/irclogger/irclogger_log/perl6?date=2019-04-19#l810). Can't say this matches my observation so far; to me, it seems to be due to the changes in #133.

**Comment by masak** [comment]
(I can't log onto IRC, by the way. _That_ may well be because of the reported DNS/network problem.)

@tadzik has [a solution here](https://colabti.org/irclogger/irclogger_log/perl6?date=2019-04-21#l238), but I'm not sure how to express that as concrete steps to make my Travis CI runs pass again. My config file just says [language: perl6](https://github.com/masak/007/blob/821fca8d06e5325fce8f376a7770b2d5e5c2f015/.travis.yml#L1); it doesn't mention rakudobrew at all. I'm at a loss how to check out v1 of rakudobrew in my Travis runs.

**Comment by patzim** [comment]
Looking into this right now.

**Comment by patzim** [comment]
I created a travis-build PR: https://github.com/travis-ci/travis-build/pull/1693
I also pinged nine and tadzik to maybe revert rakudobrew.
We'll see what happens first.

**Comment by patzim** [comment]
rakudobrew is now completely reverted to before the big overhaul. Travis testing should work again now. The Travis PR above is hopefully merged in the coming days which should pin Travis to a specific rakudobrew version, helping stability. I'm hoping this works out and does not break in some other unforseen way...

**Comment by patzim** [comment]
@masak Could you have another look if stuff actually works again?

**Comment by masak** [comment]
Yes, [all green now](https://travis-ci.org/masak/007/builds/523345944) on the original configuration. Thank you; closing.

**Comment by JJ** [comment]
This means that the master branch is broken? Should we all use v1 now?

**Comment by patzim** [comment]
@JJ No, it's not broken. Just the way to install rakudobrew has changed in a minor detail which caused the automated travis build of perl6 to fail, as it tried to install the new rakudobrew in a way only working with an old rakudobrew. See [here](https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/perl6.rb#L30). That line suffices to get the old rakudobrew somehow working but not the new one. Rakudobrew is not documented to be used that way.

**Comment by JJ** [comment]
The thing is that I also use rakudobrew for my whole set of Alpine-based containers. I'll see what's best, to use v1 or to switch to the new installation procedure.
