### ISSUE TITLE
New installation procedure does not seem to work with zshell

### ISSUE THREAD

**Issue by JJ** [tadzik/rakudobrew#139]
This is ubuntu 16.04, and I'm using:

```
tail ~/.zsh_profile 
eval "$(/home/jmerelo/.rakudobrew/bin/rakudobrew init Zsh"
➜  ~ rakudobrew list-available
The shell hook required to use rakudobrew in 'env' mode and use the 'shell' command seems not to be installed.
Run 'rakudobrew init' for installation instructions.
```

That's in a new shell. It's also copied in .profile, does not do a thing either.

**Comment by JJ** [comment]
OK, I'm seen the missing closing parenthesis now.

**Comment by JJ** [comment]
Does not matter. Same difference.

**Comment by JJ** [comment]
If I run that line on the interactive shell, it install rakudobrew in the shell; it does not work from the .profile or .zsh_profile

**Comment by patzim** [comment]
Fixed as stated in commits seen above.
