### ISSUE TITLE
switch doesn't work after the latest update

### ISSUE THREAD

**Issue by vrurg** [tadzik/rakudobrew#146]
With the latest update it builds the requested rakudo. But nothing happens upon `switch` to that version. It was used to install symlinks in `~/.rakudobrew/bin` but not anymore. When I decided to recheck `init` instructions there was paths to the built rakudo version in the recommended `PATH`.

macOS, fish shell. Sorry, no time for better diagnostics.

**Comment by patzim** [comment]
What you see is the new behavior of rakudobrew in `env` mode. In `env` mode rakudobrew doesn't rely on shims, but modifies the `$PATH` variable in place. For this to work you need to install the shell hook as instructed (see `rakudobrew init`).

If you want rakudobrew to use shims as it did in the previous version you have to change the mode to `shim`. use `rakudobrew mode shim` to do that. Also note, that the shims do not reside in `~/.rakudobrew/bin` anymore but in `~/.rakudobrew/shims`.

Please reopen if the above does not fully explain the behaviour you see.

**Comment by vrurg** [comment]
Just for a note. The hook was installed but something went wrong. I switched over to shims mode. This way it works. Almost. `rakudobrew switch system` doesn't work for me. I ignore this because for a long time is using own shortcut to switch off rakudobrew. :)

**Comment by patzim** [comment]
@vrurg Can you tell what goes wrong with `rakudobrew switch system`? It doesn't remove the shims when switching to system (because they are still needed for local versions to work), but the shims should correctly forward to the system perl6.
Also do you know what went wrong with the hook? I'd like to get this working in all environments...

**Comment by vrurg** [comment]
My rakudo is installed in `~/perl6`. With `rakudobrew switch system` `which perl6` is `/Users/vrurg/.rakudobrew/shims/perl6` – as it expected to be. But `perl6 -v` ends up with:

```
/Users/vrurg/.rakudobrew/shims
/Users/vrurg/perl6/bin
Can't exec "/Users/vrurg/.rakudobrew/shims": Permission denied at /Users/vrurg/.rakudobrew/shims/perl6 line 567.
Executing /Users/vrurg/.rakudobrew/shims failed with: Permission denied at /Users/vrurg/.rakudobrew/shims/perl6 line 568.
```

**Comment by patzim** [comment]
I'll look into this.

**Comment by vrurg** [comment]
What a coincidence! I `self-upgrade`'d `rakudobrew` a couple of minutes ago and can confirm that it's working now.

**Comment by vrurg** [comment]
Thanks a lot!
