### ISSUE TITLE
rakudobrew build moar - Can't locate NQP/Config.pm

### ISSUE THREAD

**Issue by Digicrat** [tadzik/rakudobrew#151]
This is on an Ubuntu 19.04 VM with the latest Rakudobrew.

```
rakudobrew build moar

HEAD is now at 8fa2b0f6a [release] Bump VERSION to 2019.11

Updating nqp-configure submodule...
Can't locate NQP/Config.pm in @INC (you may need to install the NQP::Config module) (@INC contains: /home/vagrant/.rakudobrew/versions/moar-2019.11/tools/lib /home/vagrant/.rakudobrew/versions/moar-2019.11/3rdparty/nqp-configure/lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at Configure.pl line 44.

BEGIN failed--compilation aborted at Configure.pl line 44.

Failed running /usr/bin/perl Configure.pl --backends=moar --gen-moar --git-reference="/home/vagrant/.rakudobrew/git_reference" --make-install  at /home/vagrant/.rakudobrew/bin/../lib/Rakudobrew/Build.pm line 46.

```

There is a ~/.rakudobrew/git_reference/nqp/tools/lib/NQP/Config/NQP.pm

I also found https://github.com/perl6/nqp/issues/581 that may be related.  Is rakudobrew pulling the wrong tarball, or otherwise missing an updated build step somewhere?

**Comment by patzim** [comment]
@Digicrat If I interpret the output you pasted correctly, the submodule update failed silently.

Can you try the following and paste the output? :

    cd /home/vagrant/.rakudobrew/versions/moar-2019.11
    git submodule sync 3rdparty/nqp-configure && git submodule --quiet update --init 3rdparty/nqp-configure

**Comment by Digicrat** [comment]
Yep, it looks like that was the issue.  Despite the original clone somehow working (I must've done it from my native machine), the submodule clone was failing due to GnuTLS issues related to an annoying enterprise proxy here.  Once I worked around that issue (which required more effort than it should've), things behaved as expected.

Not suppressing the error (which I see you pushed a fix for) should clear up confusion in the future.  Thanks for the quick response.
