### ISSUE TITLE
Refactoring for testing

### ISSUE THREAD

**Issue by JJ** [tadzik/rakudobrew#18]
Wonder if it would be worth the while to refactor the main part of the script to a module so that every function can be tested independently, as Chromatic says here in Perl Monks http://www.perlmonks.org/?node_id=858958. Another option would be to use [`Test::Script::Run`](http://search.cpan.org/~sunnavy/Test-Script-Run-0.08/lib/Test/Script/Run.pm), also mentioned there.

**Comment by JJ** [comment]
Maybe it's the moment to pick this up again?

**Comment by JJ** [comment]
Or maybe now?

**Comment by patzim** [comment]
Rakudobrew is now split into different modules. I'm not that proficient in module structure in perl5 so the way it's done might not be the cleverest.
