### ISSUE TITLE
'rakudobrew build all' fails due to --gen-parrot

### ISSUE THREAD

**Issue by avuserow** [tadzik/rakudobrew#31]
Asking rakudobrew to build all backends fails now due to a lack of --gen-parrot.

**Comment by ugexe** [comment]
#29

**Comment by tadzik** [comment]
#29 merged, so this is now closable.

I worry a bit about people who actually use rakudo-parrot and expect it to be there, but they probably don't use rakudobrew anyway (or we'll know soon enough).
