### ISSUE TITLE
build-panda task tells me panda's up to date, but then proceeds to build it

### ISSUE THREAD

**Issue by uvtc** [tadzik/rakudobrew#37]
Haven't run `rakudobrew build moar` in a while. After doing so, did this:

~~~
$ rakudobrew build-panda
Already up-to-date.
==> Bootstrapping Panda
==> Fetching File::Find
==> Building File::Find
Compiling lib/File/Find.pm to mbc
==> Testing File::Find
t/01-file-find.t .. ok
{snip}
~~~

So, it gives me the impression that its panda is up to date, but then it goes on to rebuild it anyway.

**Comment by ugexe** [comment]
Panda might be up to date, but its dependencies may not be or may need to be rebuilt for some other reason. The 'Already up-to-date' message is the result of calling the 'git' command and just means the repo is up to date.

**Comment by uvtc** [comment]
Ah. Thanks. Would be informative if git told you the message was from git. Thanks.

**Comment by tadzik** [comment]
Fixed, thanks :)
