### ISSUE TITLE
After build-panda, told to add moar-nom/install/share/perl6/site/bin to $PATH

### ISSUE THREAD

**Issue by uvtc** [tadzik/rakudobrew#38]
After running `rakudobrew build-panda`, noticed this at the end:

```
==> Successfully installed panda
==> Please make sure that /home/john/.rakudobrew/moar-nom/install/share/perl6/site/bin is in your PATH
==> Reinstalling 
Done, built panda for moar-nom
Updating shims
```

Is that correct? Do I really need to add that to my PATH? I've already got ~/.rakudobrew/bin on my PATH and it seems to work fine...

(I also notice another bin dir in there: ~/.rakudobrew/moar-nom/install/bin )

**Comment by ugexe** [comment]
That is a message from panda, which has no idea rakudobrew is also installing a copy of itself to another location already in PATH.

**Comment by tadzik** [comment]
Yeah, what @ugexe says; this message is still valid when you install panda yourself; perhaps it can be reworded in some way to better reflect the actual usage of it? Opinions, ideas?

**Comment by uvtc** [comment]
Maybe, "Please make sure that $foo is in your PATH, unless a tool (such as rakudobrew) is managing panda's location."

**Comment by patzim** [comment]
Panda is long dead. Closing.
