### ISSUE TITLE
Warn about non-functioning parrot build?

### ISSUE THREAD

**Issue by sjn** [tadzik/rakudobrew#46]
17:15  * sjn notes that "rakudobrew build parrot" doesn't work any more
17:16 < sjn> It bails with the error "Unknown option: gen-parrot"
17:16 < JimmyZ_> sjn: it is known 
17:16 < sjn> perhaps turn off the parrot option in rakudobrew?
17:17 < tadzik> Please open a ticket :)
17:17 < sjn> or at least add a short statement that it's for people who want to hack on it to make it work again :)
17:17 < tadzik> And query me, because I want to query you but my mobile client can't

Done! ^^

**Comment by tadzik** [comment]
It seems like it's fixed for a while, since March 29th: https://github.com/tadzik/rakudobrew/commit/026abf814691dbb13f0d1e9203a59ab3713ef00c

From that commit on, I get ```Building Rakudo with backend 'parrot' is NYI. Well volunteered!```. Are you sure your rakudobrew is up-to-date? You can update it with ```rakudobrew self-upgrade```

**Comment by coke** [comment]
I would recommend changing this error to say

```
Cannot build Rakudo with backend 'foobar': this backend does not exist.
```

and _maybe_ making it say

```
Cannot build Rakudo with backend 'parrot': this backend is no longer supported.
```

if they use parrot specifically.

Happy to put a PR together for this if you agree.

**Comment by tadzik** [comment]
Sounds good to me :)
