### ISSUE TITLE
perl6-j should not required `rakudobrew switch jvm` first

### ISSUE THREAD

**Issue by ugexe** [tadzik/rakudobrew#53]
Unless you explicitly switch to a different VM the shims that point to a different VM do not work:

```
<after `rakudobrew build jvm` and `rakudobrew rehash`>
rakudobrew: perl6-j: command not found

The 'perl6-j' command exists in these Perl 6 versions:

jvm-nom
```

**Comment by tadzik** [comment]
Indeed. Would you rather have those shims not available at all, or autoswitch when requested? I wonder if the latter would always be desirable, especially in case of binaries installed from the module ecosystem.

**Comment by coke** [comment]
The current behavior doesn't seem unreasonable to me; if you have a build that is for a specific VM, you have to be using that build to use that VM.

**Comment by ugexe** [comment]
I would agree with that. What I suppose I would like to see (and this may need work in rakudo itself) is a way to build both the moar and jvm backends for a specific build into the same folder
