### ISSUE TITLE
Symlinking the rakudobrew script to a directory on the path wipes out the contents of that directory.

### ISSUE THREAD

**Issue by bitmonger** [tadzik/rakudobrew#56]
Instead of adding ~/.rakudobrew/bin to my path, as the tutorial says, I instead symlinked the script to ~/bin.  This had the effect of dumping a whole bunch of new files in my home directory and also wiping the contents of ~/bin.  

Suggestion: add a "readlink -m" equivalent when canonicalizing the path to the script.

**Comment by shadowcat-mst** [comment]
We just had the fine and wonderful joy of a user who symlinked it into /usr/bin - they're currently learning more about arch linux than I think they were expecting to today.

http://sherlock.scsys.co.uk/~matthewt/rakudoboo

switches from $Bin to $RealBin as equivalent to the readlink, but also tries to only unlink things that it created.

**Comment by mortie** [comment]
User who symlinked to/ust/bin here. That was fun.

**Comment by zoffixznet** [comment]
Converted the patch into a PR: https://github.com/tadzik/rakudobrew/pull/72
