### ISSUE TITLE
"rakudobrew triple" fails with "Couldn't determine correct make program. Aborting."

### ISSUE THREAD

**Issue by smls** [tadzik/rakudobrew#63]
The `triple` commands does not seem to be able to build the latest nqp.

I tried it with both of the following combinations:

```
rakudobrew triple
rakudobrew triple nom master master
```

The result is the same: It builds moar, but apparently can't build nqp. The last few lines of output are:

```
Found ../install/bin/moar version 2015.09-86-g071e0a6, which is new enough.
Cleaning up ...
You can now use 'make' to build NQP.
After that, 'make test' will run some tests and
'make install' will install NQP.
Couldn't determine correct make program. Aborting.
```

**Comment by zoffixznet** [comment]
Same issue here still. TimToady made this patch last year but when I tried applying it right now, I still got errors about calling make on 'null object': https://gist.githubusercontent.com/TimToady/0b68b598b74df83e1eee/raw/fde36d40813f7d9421462c89ba23060694efa7e9/gistfile1.txt

**Comment by patzim** [comment]
This is still failing in 2019. Incredible. Will look into this.
