### ISSUE TITLE
List dependencies

### ISSUE THREAD

**Issue by dnmfarrell** [tadzik/rakudobrew#78]
Rakudobrew requires both Git and Perl to be installed before it will work. Especially on Windows these two are not present by default. The installation instructions fail if Perl is not present with an unhelpful error message (`'perl' is not recognized as an internal or external command,
operable program or batch file.`).

The user should install Strawberry Perl / Activestate Perl and [Git for Windows](https://www.git-scm.com/downloads). Then follow the installation instructions.

**Comment by tadzik** [comment]
True; would you say a note in the README is a sufficient documentation for this?
