### ISSUE TITLE
Why in a dot-directory?

### ISSUE THREAD

**Issue by remorse** [tadzik/rakudobrew#83]
Hi! Why are you installing into `.rakudobrew`? Why does this need to be in a dot-directory?

Thanks,
Ricky

**Comment by tadzik** [comment]
Hi,
I don't usually like my $HOME polluted with directories created by thousands of different programs and tools, I always appreciate when then "hide" themselves, so I use that in rakudobrew's examples. There is nothing stopping you from using a different location though, rakudobrew should work just fine if you clone it to a non-dot directory :)
